latency-wait: "{{cookiecutter.latency_wait}}"
use-conda: {{cookiecutter.use_conda}}
use-singularity: {{cookiecutter.use_singularity}}
restart-times: {{cookiecutter.restart_times}}
jobs: {{cookiecutter.jobs}}
cluster: "lsf-submit.py"
cluster-status: "lsf-status.py"
