latency-wait: "{{cookiecutter.latency_wait}}"
use-conda: {{cookiecutter.use_conda}}
keep-going: {{cookiecutter.keep_going}}
restart-times: {{cookiecutter.restart_times}}
jobs: {{cookiecutter.jobs}}
cluster-sync: "sync-submit.py"
local-cores: 1
